version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  web:
    environment:
      - RAILS_ENV
      - SECRET_KEY_BASE
      - RAILS_SERVE_STATIC_FILES
      - RAILS_LOG_TO_STDOUT
    build: .
    command: bundle exec rails s -p 29180 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "29180:29180"
    depends_on:
      - db
